// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdxN0duwNb0gvH2ZYJ9nNrPIwVVzYeyto',
    appId: '1:375632463645:web:d6b97f85424456e01183f4',
    messagingSenderId: '375632463645',
    projectId: 'stealth-30c79',
    authDomain: 'stealth-30c79.firebaseapp.com',
    storageBucket: 'stealth-30c79.firebasestorage.app',
    measurementId: 'G-0753163TTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp5LM2q42qwbhFrFWnXk9lrPiO1sIZrHM',
    appId: '1:375632463645:android:98897468a11153fb1183f4',
    messagingSenderId: '375632463645',
    projectId: 'stealth-30c79',
    storageBucket: 'stealth-30c79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzvuQHIg2DyQrZu1JyiEdkeQU0pDdFRO0',
    appId: '1:375632463645:ios:75ec238b6c31c6d81183f4',
    messagingSenderId: '375632463645',
    projectId: 'stealth-30c79',
    storageBucket: 'stealth-30c79.firebasestorage.app',
    iosBundleId: 'com.param.stealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzvuQHIg2DyQrZu1JyiEdkeQU0pDdFRO0',
    appId: '1:375632463645:ios:565484df9efe5d981183f4',
    messagingSenderId: '375632463645',
    projectId: 'stealth-30c79',
    storageBucket: 'stealth-30c79.firebasestorage.app',
    iosBundleId: 'com.example.stealthFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdxN0duwNb0gvH2ZYJ9nNrPIwVVzYeyto',
    appId: '1:375632463645:web:fee5a4b716946e4c1183f4',
    messagingSenderId: '375632463645',
    projectId: 'stealth-30c79',
    authDomain: 'stealth-30c79.firebaseapp.com',
    storageBucket: 'stealth-30c79.firebasestorage.app',
    measurementId: 'G-ESVTW2ND73',
  );
}
